// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdZU5UoZ2qsZrXbrx96mddnt3W1tS5Ws8',
    appId: '1:888113065281:web:c253a5e10b4e6c9830c5c0',
    messagingSenderId: '888113065281',
    projectId: 'health-rootz',
    authDomain: 'health-rootz.firebaseapp.com',
    storageBucket: 'health-rootz.firebasestorage.app',
    measurementId: 'G-WTNSY1R119',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEjY43vp2dhI9AaeCy91RDY0VsegiJ0do',
    appId: '1:888113065281:android:9d34c38227d189f930c5c0',
    messagingSenderId: '888113065281',
    projectId: 'health-rootz',
    storageBucket: 'health-rootz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6nK8vbDx4x6FdhGR_A7Gzy0t64SGZzZs',
    appId: '1:888113065281:ios:b56e838919714ec530c5c0',
    messagingSenderId: '888113065281',
    projectId: 'health-rootz',
    storageBucket: 'health-rootz.firebasestorage.app',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6nK8vbDx4x6FdhGR_A7Gzy0t64SGZzZs',
    appId: '1:888113065281:ios:b56e838919714ec530c5c0',
    messagingSenderId: '888113065281',
    projectId: 'health-rootz',
    storageBucket: 'health-rootz.firebasestorage.app',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdZU5UoZ2qsZrXbrx96mddnt3W1tS5Ws8',
    appId: '1:888113065281:web:c63df0623f59682a30c5c0',
    messagingSenderId: '888113065281',
    projectId: 'health-rootz',
    authDomain: 'health-rootz.firebaseapp.com',
    storageBucket: 'health-rootz.firebasestorage.app',
    measurementId: 'G-PQFKCX7V9V',
  );
}
